name: chocolatine

on:
  push:
    branches-ignore:
      -ga-ignore-*
    pull-request:
      branches-ignore:
        -ga-ignore-*

jobs:
  Unwanted_file_detected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: find . -name *.o
      - run: find . -name *.a
      - run: find . -name *.so
      - run: find . -name *.gcno
      - run: find . -name *.gcda
      - run: find . -name *.gcov
      - name: .gcda
        run: |
          FILE2=$(find . -name *.gcda)
          if [[ -n "$FILE2" ]]; then
          echo "::error file=$FILE2,line=1,col=5,endColumn=7::$FILE2"
          fi
      - name: .o
        run: |
          FILE2=$(find . -name *.o)
          if [[ -n "$FILE2" ]]; then
          echo "::error file=$FILE2,line=1,col=5,endColumn=7::$FILE2"
          fi
      - name: .a
        run: |
          FILE2=$(find . -name *.a)
          if [[ -n "$FILE2" ]]; then
          echo "::error file=$FILE2,line=1,col=5,endColumn=7::$FILE2"
          fi
      - name: .gcno
        run: |
          FILE2=$(find . -name *.gcno)
          if [[ -n "$FILE2" ]]; then
          echo "::error file=$FILE2,line=1,col=5,endColumn=7::$FILE2"
          fi
      - name: .so
        run: |
          FILE2=$(find . -name *.so)
          if [[ -n "$FILE2" ]]; then
          echo "::error file=$FILE2,line=1,col=5,endColumn=7::$FILE2"
          fi
      - name: .gcov
        run: |
          FILE2=$(find . -name *.gcov)
          if [[ -n "$FILE2" ]]; then
          echo "::error file=$FILE2,line=1,col=5,endColumn=7::$FILE2"
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    steps:
      - run: make
        queue:
          timeoutInMinutes: 120
      - run: make fclean
      - run: |
          IFS=','
          exit_status=0
          for file in ${EXECUTABLES}
          do
              if [ -x "$file" ]; then
                  if [ ! -d "$file" ]; then
                      echo "File '$file' is executable"
                  else
                      echo "File '$file' is directory"
                      exit_status=84
                  fi
              else
                  echo "File '$file' is not executable"
                  exit_status=84 
              fi
          done
          exit $exit_status
          
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-taha.alani.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
