name: size
on: [push]
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: echo "${GITHUB_REF#refs/heads/}"
      - run: du -skh --exclude=".git"
